# Generated by Django 3.2.9 on 2021-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('username', models.CharField(max_length=128)),
            ],
        ),
    ]
