# Generated by Django 3.2.9 on 2021-11-26 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aff3432d-31df-4a02-8e7a-2c8959988b5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
