# Generated by Django 3.2.9 on 2021-11-27 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a61ee90-d26b-4697-ba3b-b851427bc68c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
