# Generated by Django 3.2.9 on 2021-12-01 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211127_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adf1a3e1-bbb2-4030-85da-59898f6665d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
