version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: python:3.7
        environment:
          DATABASE_URL: postgis://postgres@localhost/social

      - image: circleci/postgres:10.1-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: social

    working_directory: ~/social

    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -U -r requirements.txt
              pip install flake8

              # install gdal for postgis
              sudo apt update
              sudo apt install -y libgdal-dev
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
